name: Pushed To The Edge
favicon: null
layout_spectrum: 0.6606751990038902
typography_spectrum: 0.51689
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8125
  lightness: 0.27875856310129166
  saturation: 0.625
  rhythmicContrast: 0.2651574194896966
purpose: []
